########## script 3 in APOE4 impairs myelination via cholesterol dysregulation in oligodendrocytes ##########
#############################################################################################################
source('../functions/plotting.r')
source('../functions/pathway_analyses.r')

##### required libraries ####
library('readxl')
library('ComplexHeatmap')
library('circlize')
library('tidyr')

# import data generated by pathway_analyses.r
data = readRDS('../data/other_analyses_outputs/pathway_scores.rds')
mat = data[['GO_BP']][['scores_filtered']]
mat2 = data[['APOE']][['scores_filtered']]
mat3 = data[['lipid']][['scores_filtered']]

# import the renamed-pathway names
print('importing pathway data')
path_names_go = as.data.frame(read_excel('../data/supplementary_tables/all_path_names_go_renaming.xlsx', sheet = 'all_path_names_go_renaming'))
rownames(path_names_go) = path_names_go$name
path_names_apoe = as.data.frame(read_excel('../data/supplementary_tables/all_path_names_go_renaming.xlsx', sheet = 'apoe_terms'))
rownames(path_names_apoe) = path_names_apoe[,'full name']
path_names_lipid = as.data.frame(read_excel('../data/supplementary_tables/all_path_names_go_renaming.xlsx', sheet = 'lipid_terms'))
rownames(path_names_lipid) = path_names_lipid[,'full name']
names = read.csv('../data/supplementary_tables/sele_pathways.csv')[,1]

# draw heatmap for all GO pathways
print('drawing heatmaps - GO')
unique = mat[unname(rowSums(abs(mat)>1.3)==1),]
shared_2 = mat[unname(rowSums(abs(mat)>1.3)>1),]

h1 = get_go_hmap(unique, names,path_names_go, 'shortened name')
h2 = get_go_hmap(shared_2, names,path_names_go, 'shortened name')

pdf('../plots/hmap_go_f1.pdf', height = 8, width = 5.5)
draw(h1%v%h2)
dev.off()

# draw heatmap for APOE-associated pathways
print('drawing heatmaps - APOE')g
temp = as.data.frame((abs(mat2)>1.3) * sign(mat2))
temp_order = rownames(temp[order((temp$Ex),(temp$In), (temp$Ast), (temp$Mic), (temp$Oli), (temp$Opc), decreasing = T),])

name = rownames(mat2)
names = lapply(rownames(mat2), function(name)
ifelse(sum(sapply(c('sterol', 'steroid','acyl','lipid','lipo', 'chylom', 'fat', 'trigly'), grepl, name))>0, 'lipid',
ifelse(sum(sapply(c('amyloid','holo'), grepl, name))>0, 'amyloid',
ifelse(sum(sapply(c('dendrit', 'synaptic','behavior','memory', 'anion','neuron'), grepl, name))>0, 'synapse',
ifelse(sum(sapply(c('defense', 'immune', 'viral','coagulation', 'platelet', 'virion','inflammatory'), grepl, name))>0, 'immune',
ifelse(sum(sapply(c('protein'), grepl, name))>0, 'protein metabolism',
ifelse(sum(sapply(c('growth', 'endothelial', 'epithelial'), grepl, name))>0, 'differentiation',
   ifelse(sum(sapply(c('alcoh'), grepl, name))>0, 'alcohol metabolism','other'))))))))
names = unname(unlist(names))
mat2 = mat2[temp_order,c('Ex','In','Ast', 'Mic', 'Oli', 'Opc')]
cell_fun = function(j, i, x, y, width, height, fill) {
grid.text(ifelse(abs(mat2[i, j])>1.3,'x',''), x, y, gp = gpar(fontsize = 15))
}
rownames(mat2) = path_names_apoe[rownames(mat2), 'shortened name']

pdf('../plots/apoe_associated_paths_new.pdf', width = 4.7, height = 5.7)
Heatmap(as.matrix(mat2), width = 2.5,colorRamp2(c(-2,0,2), c('blue','white','red')),cluster_rows = F, cluster_columns = F, border = T, cell_fun = cell_fun) #row_split = names)
dev.off()

# draw heatmaps for lipid-associated pathways
print('drawing heatmaps - lipid associated')
names = unique(unname(unlist(lapply(names(mat3$all), function(x) rownames(mat3$all[[x]])))))

temp = as.data.frame((abs(mat3)>1.3) * sign(mat3))
temp_order = rownames(temp[order((temp$Ex),(temp$In), (temp$Ast), (temp$Mic), (temp$Oli), (temp$Opc), decreasing = T),])

df = mat3[temp_order,c('Ex','In','Ast', 'Mic', 'Oli', 'Opc')]
cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(ifelse(abs(df[i, j])>1.3,'x',''), x, y, gp = gpar(fontsize = 15))
}

options(repr.plot.width = 4.7, repr.plot.height = 5, repr.plot.res = 150)
rownames(df) = path_names_lipid[rownames(df), 'shortened name']

pdf('../plots/lipid_paths.pdf', width = 4.7, height = 4.7)
Heatmap(as.matrix(df), width = 2.5,colorRamp2(c(-2,0,2), c('blue','white','red')),cluster_rows = F, cluster_columns = F, border = T, cell_fun = cell_fun) #row_split = names)
dev.off()

print('done')
